#+title:  User manuals and documentation for Centos Virtual Labs platform
#+SETUPFILE: ./org-templates/level-0.org

* Introduction

This is the opening page of the User level documentation for the Centos Virtual Labs platform installation and configuration.

* Pre-requisites for a Integration Engineer

Following assumptions are made before going ahead with the setup and deployment process:

A system equipped and installed with CentOS 6.5 or a higher version.
If not, the installation can be carried out through the following link:
[[http://www.centos.org/download/][Download CentOS]] 


following technical expertise is expected from an integration engineer. Operating on the basic shell commnads on CentOS operating system 
- Basic understanding of Virtualization
- Ease of working with web technologies like HTML, JavaScript etc.

* Documentation 
Browsing over the "user-docs", 
you will find documentation on the followig:

- [[./setup-centos.org][How to Setup Centos as a Virtual Lab Deployment Platform]]  ::
    Contains instructions on setting CentOS machine as a virtual
    lab deployment platform.

- [[./faq.org][FAQ on CentOS and OVPL Installation]] :: 
    Common questions about CentOS and Python module installation.


- [[./intro-to-openvz.org][Introduction to OpenVZ]] :: 
    An introduction to virtualization with OpenVZ.
     
