#+title:  User Documentation for Setting-up OVPL on CentOS
#+SETUPFILE: ./org-templates/level-0.org

* Introduction

Welcome to the user documentation for CentOS Virtual Labs platform installation and configuration. As an integration engineer, this documentation will guide you through the steps to set up OVPL on CentOS.

* Pre-requisites for Setting-up OVPL on CentOS

You need to adhere to the following hardware and software requirements for setting up OVPL:

- Minimum 2GB RAM
- A dedicated partition for CentOS (version 6.5 only)
- Minimum 50GB hard disk space
- A dual core processor
In case you do not have CentOS 6.5 or a higher version, you can install the same through the following link:
[[http://www.centos.org/download/][Download CentOS]] 

* Assumptions about Users
For setting up OVPL on CentOS, you are expected to know how to execute basic shell commands in CentOS 6.5, create and delete a container in openVZ virtual environment, create or modify an HTML page and write a code in JavaScript.

As an integration engineer, you are expected to know how to use GitHub - a subversioning tool. Here is a small tutorial to revise your concepts about GitHub. <>?? 

* User Documentation - What to find Where? 
After browsing through the "user-docs", you will find documentation about the following:

- [[./setup-centos.org][How to Set Up CentOS as a Virtual Lab Deployment Platform]]  ::
    This contains instructions about setting CentOS machine as a virtual
    lab deployment platform.

- [[./faq.org][FAQ on CentOS and OVPL Installation]] :: 
    This has some frequently asked common questions about CentOS and Python module installation.


- [[./intro-to-openvz.org][Introduction to OpenVZ]] :: 
    This is an introduction to virtualization using OpenVZ.
     
